service:
  golangci-lint-version: 1.64.5
run:
  deadline: 900s
  modules-download-mode: readonly
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - execinquery
    - exportloopref
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - err113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - importas
    - interfacebloat
    - ireturn
    - maintidx
    - makezero
    - mnd
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - revive
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/viamrobotics/agent-provisioning)
  gofumpt:
    extra-rules: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
      - composites
  lll:
    line-length: 140
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - dupword
        - errcheck
        - exhaustive
        - goconst
        - gosec
    - path: ^cmd/provisioning-client/
      linters:
        - forbidigo
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
