version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  default: standard
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - inamedparam
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint


  settings:
    errcheck:
      check-blank: true
    goconst:
      ignore-string-values:
        - '^windows$'
    gomoddirectives:
      replace-allow-list:
        - github.com/hashicorp/go-getter
    govet:
      disable:
        - fieldalignment
        - shadow
        - composites
      enable-all: true
    lll:
      line-length: 140
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -QF1008
        - -QF1001
        - -QF1006
        - -QF1012
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupword
          - errcheck
          - exhaustive
          - goconst
          - gosec
        path: _test\.go$
      - linters:
          - forbidigo
        path: ^cmd/provisioning-client/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/viamrobotics/agent-provisioning)
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
