# Uncommented fields are required. Text <in brackets> is a placeholder and
# should be replaced with appropriate values.

api_key_id = "<app location api key id with owner role>"
api_key = "<app location api key with owner role>"
robot_id = "<robot id>"
part_id = "<part id>"

[versions]
viam_agent_stable = '0.25.0'
# viam_agent_stable_url = "<optional file:// or https:// URL to use instead of the 'stable' magic string when pinning back to stable>"
viam_agent_old = '0.24.2'
viam_agent_old_url = "<GCS URL for old viam-agent binary, required for agent-url.feature>"
viam_server_old = "<old viam-server version string, required for viamserver-version.feature>"
viam_server_old_url = "<GCS URL for old viam-server binary, required for viamserver-version.feature>"

# serial_path = "<path to serial device, on Linux usually starts with /dev/ttyUSB>"

# [wifi]
# ssid = "<wifi ssid>"
# password = "<wifi password>"
