# Uncommented fields are required. Text <in brackets> is a placeholder and
# should be replaced with appropriate values.

api_key_id = "<app location api key id with owner role>"
api_key = "<app location api key with owner role>"
robot_id = "<robot id>"
part_id = "<part id>"

[versions]
viam_agent_stable = '0.25.0'
viam_agent_old = "<old viam-agent version string, required for agent-pin-url.feature and agent-pin-file.feature>"
viam_server_old = "<old viam-server version string, required for viamserver-pin-*.feature>"

# serial_path = "<path to serial device, on Linux usually starts with /dev/ttyUSB>"

# [wifi]
# ssid = "<wifi ssid>"
# password = "<wifi password>"
