# Required fields
api_key_id = "<app api key id taken from machine install instructions>"
api_key = "<app api key taken from machine install instructions>"
part_id = "<part id>"

# # Optional fields
# serial_path = "<path to serial device, on Linux usually starts with /dev/ttyUSB>"

# [wifi]
# ssid = "<wifi ssid>"
# password = "<wifi password>"

# [ble]
# env_file = "<path to .env file for BLE provisioning test>"
