[tools]
go = "1.26"
golangci-lint = "2.9.0"
shfmt = "3.12.0"

[tasks.fmt-sh]
run = "shfmt -w *.sh"

[tasks.lint]
run = [
  'go mod tidy',
  'GOOS=linux golangci-lint run -v --fix --timeout 10m',
  'GOOS=windows golangci-lint run -v --fix --timeout 10m',
]

[tasks.test-e2e-serial]
description = "Run tests on a real device connected via serial. See readme for setup requirements."
run = "go test . -count 1 -v -timeout 30m -run TestSerialFeatures -tags=serialtests"
