name: Build Agent MSI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download agent binary
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest `
            -Uri "https://storage.googleapis.com/packages.viam.com/apps/viam-agent/viam-agent-stable-windows-x86_64" `
            -OutFile msi\viam-agent-from-installer.exe `
            -UseBasicParsing

      - name: Build MSI
        shell: pwsh
        run: |
          dotnet tool restore
          dotnet build msi -c Release

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: viam-agent-msi
          path: msi/bin/x64/Release/Package.msi
